name: Tweet New Entries

on:
  push:
    branches:
    - master
    - action
    - ci

jobs:
  tweet:
    name: Tweet new entries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Run tweet action tests
      uses: ./.github/actions/tweet-commit
      with:
        args: test
    - name: Send Tweet if requested in commit message
      uses: ./.github/actions/tweet-commit
      with:
        trigger_keyword: TweetMe!
        twitter_api_key: "${{ secrets.twitter_api_key }}"
        twitter_api_secret_key: "${{ secrets.twitter_api_secret_key }}"
        twitter_access_token: "${{ secrets.twitter_access_token }}"
        twitter_access_token_secret: "${{ secrets.twitter_access_token_secret }}"
